version: 2

timeout: 90

parameters:
  RBENV_PATHS: "/Users/tools/.rbenv/bin:/Users/tools/.rbenv/shims"
  LANGUAGE: en_US.UTF-8
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8

defaults:
  platform: "ios-client"
  plugins:
    mail: {}
    logparser:
      rules: minimal

workflows:
  build_and_deploy_mistica_catalog:
    platform: macslave-prod-5 # the osx dedicated to mistica
    stages: ["unistall_prov_profiles_and_cert", "install_prov_profiles_and_cert", "setup_ruby", "setup_project_dependencies", "build_and_deploy_mistica_catalog", "check_prov_profiles_and_cert_expiry_day"]
    parameters:
      # Parameters for cert & profiles management scripts
      INSTALL_PROV_PROFILES: '-i'
      UNINSTALL_PROV_PROFILES: '-u'
      BRAND_VARIANT: 'MisticaApp'
    plugins:
      mail:
        enabled: True
        recipients:
          - "ios@tuenti.com"
      vault:
        secrets:
          - path: secret/services/jenkins/iOS_prov_profiles_and_certs/MisticaApp
            keys:
              Enterprise_prov_profiles: IOS_ENTERPRISE_PROV_PROFILES
              Enterprise_p12_pwd: ENTERPRISE_CERT_PWD
          - path: secret/services/jenkins/appcenter
            keys:
              appcenter_api_token: APPCENTER_API_TOKEN

stages:
  setup_ruby:
    - "rm -rf logs/*"
    - "rm -rf tmp/*"
    - "export PATH=${RBENV_PATHS}:${PATH}; rbenv install 2.6.0 || true"
    - "export PATH=${RBENV_PATHS}:${PATH}; rbenv local 2.6.0"
    - "export PATH=${RBENV_PATHS}:${PATH}; rbenv which ruby; which ruby; ruby --version"
  setup_project_dependencies:
    - "pwd"
    - "export PATH=${RBENV_PATHS}:${PATH}; gem install bundle"
    - "export PATH=${RBENV_PATHS}:${PATH}; bundle config --delete without"
    - "export PATH=${RBENV_PATHS}:${PATH}; bundle install"
    - "export PATH=${RBENV_PATHS}:${PATH}; bundle exec fastlane setup"
  build_and_deploy_mistica_catalog:
    - "export PATH=${RBENV_PATHS}:${PATH}; bundle exec fastlane build_and_deploy_mistica_catalog"
  install_prov_profiles_and_cert:
    - "./scripts/osx_prov_profiles_and_certs_mgmt/install_prov_profiles_and_cert_in_osx.sh ${INSTALL_PROV_PROFILES}"
  unistall_prov_profiles_and_cert:
    - "./scripts/osx_prov_profiles_and_certs_mgmt/install_prov_profiles_and_cert_in_osx.sh ${UNINSTALL_PROV_PROFILES}"
  check_prov_profiles_and_cert_expiry_day:
    - "./scripts/osx_prov_profiles_and_certs_mgmt/check_cert_and_prov_profiles_expiration_date.sh ${CHECK_PROV_PROFILES_DATE}"