
// Generated using Make
// DO NOT EDIT

import UIKit

public protocol MisticaColors {
    var background: UIColor { get }
    var backgroundAlternative: UIColor { get }
    var backgroundBrand: MisticaColor { get }
    var backgroundBrandSecondary: UIColor { get }
    var backgroundContainer: UIColor { get }
    var backgroundContainerError: UIColor { get }
    var backgroundContainerHover: UIColor { get }
    var backgroundContainerPressed: UIColor { get }
    var backgroundContainerBrand: MisticaColor { get }
    var backgroundContainerBrandHover: UIColor { get }
    var backgroundContainerBrandPressed: UIColor { get }
    var backgroundContainerBrandOverInverse: UIColor { get }
    var backgroundContainerAlternative: UIColor { get }
    var backgroundOverlay: UIColor { get }
    var backgroundSkeleton: UIColor { get }
    var backgroundSkeletonInverse: UIColor { get }
    var backgroundBrandTop: UIColor { get }
    var backgroundBrandBottom: UIColor { get }
    var appBarBackground: UIColor { get }
    var navigationBarBackground: UIColor { get }
    var skeletonWave: UIColor { get }
    var borderLow: UIColor { get }
    var border: UIColor { get }
    var borderHigh: UIColor { get }
    var borderSelected: UIColor { get }
    var coverBackgroundHover: UIColor { get }
    var coverBackgroundPressed: UIColor { get }
    var buttonDangerBackground: UIColor { get }
    var buttonDangerBackgroundSelected: UIColor { get }
    var buttonDangerBackgroundHover: UIColor { get }
    var buttonLinkDangerBackgroundSelected: UIColor { get }
    var buttonLinkDangerBackgroundInverse: UIColor { get }
    var buttonLinkDangerBackgroundInverseSelected: UIColor { get }
    var buttonLinkBackgroundSelected: UIColor { get }
    var buttonLinkBackgroundInverseSelected: UIColor { get }
    var buttonPrimaryBackground: UIColor { get }
    var buttonPrimaryBackgroundInverse: UIColor { get }
    var buttonPrimaryBackgroundSelected: UIColor { get }
    var buttonPrimaryBackgroundHover: UIColor { get }
    var buttonPrimaryBackgroundInverseSelected: UIColor { get }
    var buttonSecondaryBorder: UIColor { get }
    var buttonSecondaryBorderSelected: UIColor { get }
    var buttonSecondaryBackgroundHover: UIColor { get }
    var buttonSecondaryBackgroundSelected: UIColor { get }
    var buttonSecondaryBorderInverse: UIColor { get }
    var buttonSecondaryBorderInverseSelected: UIColor { get }
    var buttonSecondaryBackgroundInverseHover: UIColor { get }
    var buttonSecondaryBackgroundInverseSelected: UIColor { get }
    var textButtonPrimary: UIColor { get }
    var textButtonPrimaryInverse: UIColor { get }
    var textButtonPrimaryInverseSelected: UIColor { get }
    var textButtonSecondary: UIColor { get }
    var textButtonSecondarySelected: UIColor { get }
    var textButtonSecondaryInverse: UIColor { get }
    var textButtonSecondaryInverseSelected: UIColor { get }
    var textLink: UIColor { get }
    var textLinkInverse: UIColor { get }
    var textLinkDanger: UIColor { get }
    var textLinkSnackbar: UIColor { get }
    var textActivated: UIColor { get }
    var textBrand: UIColor { get }
    var control: UIColor { get }
    var controlActivated: UIColor { get }
    var controlInverse: UIColor { get }
    var controlActivatedInverse: UIColor { get }
    var controlError: UIColor { get }
    var barTrack: UIColor { get }
    var loadingBar: UIColor { get }
    var loadingBarBackground: UIColor { get }
    var toggleAndroidInactive: UIColor { get }
    var toggleAndroidBackgroundActive: UIColor { get }
    var iosControlKnob: UIColor { get }
    var divider: UIColor { get }
    var dividerInverse: UIColor { get }
    var navigationBarDivider: UIColor { get }
    var badge: UIColor { get }
    var feedbackErrorBackground: UIColor { get }
    var feedbackInfoBackground: UIColor { get }
    var brand: UIColor { get }
    var brandHigh: UIColor { get }
    var inverse: UIColor { get }
    var neutralHigh: UIColor { get }
    var neutralMedium: UIColor { get }
    var neutralMediumInverse: UIColor { get }
    var neutralLow: UIColor { get }
    var neutralLowAlternative: UIColor { get }
    var textPrimary: UIColor { get }
    var textPrimaryInverse: UIColor { get }
    var textSecondary: UIColor { get }
    var textSecondaryInverse: UIColor { get }
    var success: UIColor { get }
    var warning: UIColor { get }
    var error: UIColor { get }
    var textError: UIColor { get }
    var textErrorInverse: UIColor { get }
    var promo: UIColor { get }
    var highlight: UIColor { get }
    var successLow: UIColor { get }
    var warningLow: UIColor { get }
    var errorLow: UIColor { get }
    var promoLow: UIColor { get }
    var brandLow: UIColor { get }
    var successHigh: UIColor { get }
    var warningHigh: UIColor { get }
    var errorHigh: UIColor { get }
    var promoHigh: UIColor { get }
    var successHighInverse: UIColor { get }
    var warningHighInverse: UIColor { get }
    var errorHighInverse: UIColor { get }
    var promoHighInverse: UIColor { get }
    var textNavigationBarPrimary: UIColor { get }
    var textNavigationBarSecondary: UIColor { get }
    var textNavigationSearchBarHint: UIColor { get }
    var textNavigationSearchBarText: UIColor { get }
    var textAppBar: UIColor { get }
    var textAppBarSelected: UIColor { get }
    var customTabsBackground: UIColor { get }
    var tagTextPromo: UIColor { get }
    var tagTextActive: UIColor { get }
    var tagTextInactive: UIColor { get }
    var tagTextSuccess: UIColor { get }
    var tagTextWarning: UIColor { get }
    var tagTextError: UIColor { get }
    var tagBackgroundPromo: UIColor { get }
    var tagBackgroundActive: UIColor { get }
    var tagBackgroundInactive: UIColor { get }
    var tagBackgroundSuccess: UIColor { get }
    var tagBackgroundWarning: UIColor { get }
    var tagBackgroundError: UIColor { get }
    var cardContentOverlay: MisticaColor { get }
}
