name: Deploy Mistica Catalog

on:
  release:
    types: [published]
  workflow_dispatch:
        inputs:
            commit_to_deploy:
                description: 'Changeset'
                required: false
                default: ''

jobs:
  deploy-mistica-catalog:
    name: Deploy Mistica Catalog
    runs-on: self-hosted-novum-mac

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Ruby and bundle install
        uses: ruby/setup-ruby@v1
        env:
          ImageOS: macos-latest
        with:
          ruby-version: 2.6
          bundler-cache: true 
          
      - name: Carthage Cache
        uses: actions/cache@v2.1.4
        id: carthage-cache
        with:
          path: Carthage
          key: mistica-ios-carthage-${{ hashFiles('Cartfile.resolved') }}
          restore-keys: |
            mistica-ios-carthage-
                
      - name: Setup the needed external dependencies 
        run:  bundle exec fastlane setup

      # Missing step: Install profiles

      - name: Build Mistica catalog and upload to AppCenter 
        run:  bundle exec fastlane build_and_deploy_mistica_catalog


      # - name: Checkout this repo
      #   uses: actions/checkout@v2

      # - name: Checkout Telefonica/github-actions repo
      #   uses: actions/checkout@v2
      #   with:
      #     repository: Telefonica/github-actions
      #     token: "${{ secrets.NOVUM_PRIVATE_REPOS }}"
      #     path: .github/actions

      # - name: Deploy main (cigen workflow)
      #   if: ${{ github.event.inputs.commit_to_deploy == '' }}
      #   uses: ./.github/actions/novum/trigger-cigen-workflow
      #   with:
      #     workflow: build_and_deploy_mistica_catalog
      #     branch: main
      #     payload: "ticket: APPS-7169"

      # - name: Deploy commit (cigen workflow)
      #   if: ${{ github.event.inputs.commit_to_deploy != '' }}
      #   uses: ./.github/actions/novum/trigger-cigen-workflow
      #   with:
      #     workflow: build_and_deploy_mistica_catalog
      #     branch: main
      #     changeset: "${{ github.event.inputs.commit_to_deploy }}"
      #     payload: "ticket: APPS-7169"
