name: Deploy Mistica Catalog (Firebase)

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      # The branch, tag or SHA to checkout
      ref:
        required: false
        type: string

jobs:
  deploy-mistica-catalog:
    name: Build enterprise
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Telefonica/ios-github-workflows repo
        uses: actions/checkout@v4
        with:
          repository: Telefonica/ios-github-workflows
          token: "${{ secrets.NOVUM_PRIVATE_REPOS }}"
          path: .ios-github-workflows

      - name: Setup
        id: setup
        uses: ./.ios-github-workflows/.github/actions/setup-mac-dependencies
      - run: xcodebuild -version

      - name: Install certificate and provisioning profiles
        id: install-cert-and-prov
        uses: ./.ios-github-workflows/.github/actions/install-signing-certificates-and-provisionings
        with:
          certificate-base64: ${{ secrets.MISTICA_ENTERPRISE_CERTIFICATE }}
          certificate-password: ${{ secrets.MISTICA_ENTERPRISE_P12_PWD }}
          apple-enterprise-api-key-id: ${{ secrets.APPLE_ENTERPRISE_API_KEY_ID }}
          apple-enterprise-api-private-key-base64: ${{ secrets.APPLE_ENTERPRISE_API_PRIVATE_KEY }}
          apple-enterprise-api-issuer-id: ${{ secrets.APPLE_ENTERPRISE_API_ISSUER_ID }}

      - name: Export
        run: make export

      - name: Upload to Firebase App Distribution
        id: firebase-upload
        uses: ./.ios-github-workflows/.github/actions/firebase-upload
        with:
          ipa-path: ./build/ios.ipa
          release-notes: "Mistica Catalog"
          tester-groups: "tid-internal-testers, mistica-internal-testers"
          google-application-credentials: ${{ secrets.FIREBASE_DIST_CREDENTIALS_RC }}

      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
            security delete-keychain ${{ steps.install-cert-and-prov.outputs.keychain-path }}
            rm ~/Library/MobileDevice/Provisioning\ Profiles/* || true
