name: Deploy Mistica Catalog

on:
  release:
    types: [published]
  workflow_dispatch:
        inputs:
            commit_to_deploy:
                description: 'Changeset'
                required: false
                default: ''

jobs:
  deploy-mistica-catalog:
    name: Deploy Mistica Catalog
    runs-on: self-hosted-novum-mac

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: RubyGems Cache
        uses: actions/cache@v2.1.4
        with:
          path: vendor/bundle
          key: mistica-ios-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            mistica-ios-gems-
          
      - name: Carthage Cache
        uses: actions/cache@v2.1.4
        id: carthage-cache
        with:
          path: Carthage
          key: mistica-ios-carthage-${{ hashFiles('Cartfile.resolved') }}
          restore-keys: |
            mistica-ios-carthage-
      
      - name: Setup Ruby
        run: |
          export RBENV_ROOT=/usr/local/rbenv
          export PATH="${RBENV_ROOT}/bin:$PATH"
          rbenv install 2.6.0 -s
          rbenv local 2.6.0
      
      - name: Bundle Install
        run: |
          gem install bundle
          bundle config path vendor/bundle
          bundle install
                
      - name: Setup needed external dependencies 
        run:  bundle exec fastlane setup

      - name: Uninstall provisioning profiles and certificate
        run: sh ./scripts/osx_prov_profiles_and_certs_mgmt/install_prov_profiles_and_cert_in_osx.sh -u
        env:
          Enterprise_prov_profiles: ${{ secrets.MISTICA_CATALOG_ENTERPRISE_PROV_PROFILES }}
          Enterprise_p12_pwd: ${{ secrets.MISTICA_CATALOG_ENTERPRISE_CERT_PWD }}

      - name: Install provisioning profiles and certificate
        run: sh ./scripts/osx_prov_profiles_and_certs_mgmt/install_prov_profiles_and_cert_in_osx.sh -i   
        env:
          Enterprise_prov_profiles: ${{ secrets.MISTICA_CATALOG_ENTERPRISE_PROV_PROFILES }}
          Enterprise_p12_pwd: ${{ secrets.MISTICA_CATALOG_ENTERPRISE_CERT_PWD }}

      - name: Build Mistica catalog and upload to AppCenter 
        run:  bundle exec fastlane build_and_deploy_mistica_catalog
        env:
          APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}

      - name: Check provisioning profiles and certificate expiry day
        run: sh ./scripts/osx_prov_profiles_and_certs_mgmt/check_cert_and_prov_profiles_expiration_date.sh -p -c
        env:
          Enterprise_prov_profiles: ${{ secrets.MISTICA_CATALOG_ENTERPRISE_PROV_PROFILES }}
          Enterprise_p12_pwd: ${{ secrets.MISTICA_CATALOG_ENTERPRISE_CERT_PWD }}


      # - name: Checkout this repo
      #   uses: actions/checkout@v2

      # - name: Checkout Telefonica/github-actions repo
      #   uses: actions/checkout@v2
      #   with:
      #     repository: Telefonica/github-actions
      #     token: "${{ secrets.NOVUM_PRIVATE_REPOS }}"
      #     path: .github/actions

      # - name: Deploy main (cigen workflow)
      #   if: ${{ github.event.inputs.commit_to_deploy == '' }}
      #   uses: ./.github/actions/novum/trigger-cigen-workflow
      #   with:
      #     workflow: build_and_deploy_mistica_catalog
      #     branch: main
      #     payload: "ticket: APPS-7169"

      # - name: Deploy commit (cigen workflow)
      #   if: ${{ github.event.inputs.commit_to_deploy != '' }}
      #   uses: ./.github/actions/novum/trigger-cigen-workflow
      #   with:
      #     workflow: build_and_deploy_mistica_catalog
      #     branch: main
      #     changeset: "${{ github.event.inputs.commit_to_deploy }}"
      #     payload: "ticket: APPS-7169"
