name: Deploy Mistica Catalog

on:
  release:
    types: [published]
  workflow_dispatch:
        inputs:
            commit_to_deploy:
                description: 'Changeset'
                required: false
                default: ''

jobs:
  deploy-mistica-catalog:
    name: Deploy Mistica Catalog
    runs-on: self-hosted-novum-mac

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Telefonica/github-actions repo
        uses: actions/checkout@v2
        with:
          repository: Telefonica/github-actions
          token: "${{ secrets.NOVUM_PRIVATE_REPOS }}"
          path: .github/shared-actions

      - name: RubyGems Cache
        uses: actions/cache@v3.0.2
        with:
          path: vendor/bundle
          key: mistica-ios-gems-${{ hashFiles('Gemfile.lock') }}

      - name: Carthage Cache
        uses: actions/cache@v3.0.2
        id: carthage-cache
        with:
          path: Carthage
          key: mistica-ios-carthage-${{ hashFiles('Cartfile.resolved') }}

      - name: Provision Novum Mac
        uses: ./.github/shared-actions/novum/mac-provisioning
        with:
          setup-ruby: true
          brand-variant: MisticaApp
          provisioning-profiles: ${{ secrets.MISTICA_CATALOG_ENTERPRISE_PROV_PROFILES }}
          certificate-password: ${{ secrets.MISTICA_CATALOG_ENTERPRISE_CERT_PWD }}
          apple-system-certs: ${{ secrets.APPLE_CERTS }}

      - name: Setup needed external dependencies
        run:  bundle exec fastlane setup

      - name: Build Mistica catalog and upload to AppCenter
        run:  bundle exec fastlane build_and_deploy_mistica_catalog
        env:
          APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }} 
