name: Deploy Mistica Catalog

on:
  release:
    types: [published]
  workflow_dispatch:
        inputs:
            app-center-project:
              description: 'App Center app name'
              type: choice
              options:
              # Internal Enterprise:
              - Mistica-iOS
              # Alpha:
              - Mistica-SwiftUI-iOS
              required: true

jobs:
  deploy-mistica-catalog:
    name: Build enterprise
    runs-on: self-hosted-novum-mac

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Checkout Telefonica/github-actions repo
        uses: actions/checkout@v3.1.0
        with:
          repository: Telefonica/github-actions
          token: "${{ secrets.NOVUM_PRIVATE_REPOS }}"
          path: .github/actions

      - name: Provision Novum Mac for MisticaApp
        uses: ./.github/actions/novum/mac-provisioning
        with:
          setup-ruby: false
          brand-variant: MisticaApp
          provisioning-profiles: ${{ secrets.MISTICA_CATALOG_ENTERPRISE_PROV_PROFILES }}
          certificate-password: ${{ secrets.MISTICA_CATALOG_ENTERPRISE_CERT_PWD }}
          apple-system-certs: ${{ secrets.APPLE_CERTS }}

      - name: Export
        run: make export

      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.13.0

      - name: Upload ipa to AppCenter
        run: npx -p appcenter-cli appcenter distribute release -a Tuenti-Organization/${{ github.event.inputs.app-center-project || 'Mistica-iOS' }} -f ./build/ios.ipa -g Public --token ${{ secrets.APPCENTER_API_TOKEN }}

