name: Deploy Mistica Catalog

on:
  release:
    types: [published]
  workflow_dispatch:
        inputs:
            commit_to_deploy:
                description: 'Changeset'
                required: false
                default: ''

jobs:
  deploy-mistica-catalog:
    name: Build enterprise
    runs-on: self-hosted-novum-mac

    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0

      - name: Checkout Telefonica/github-actions repo
        uses: actions/checkout@v3.2.0
        with:
          repository: Telefonica/github-actions
          token: "${{ secrets.NOVUM_PRIVATE_REPOS }}"
          path: .github/actions

      - name: Provision Novum Mac for MisticaApp
        uses: ./.github/actions/novum/mac-provisioning
        with:
          setup-ruby: false
          brand-variant: MisticaApp
          provisioning-profiles: ${{ secrets.MISTICA_CATALOG_ENTERPRISE_PROV_PROFILES }}
          certificate-password: ${{ secrets.MISTICA_CATALOG_ENTERPRISE_CERT_PWD }}
          apple-system-certs: ${{ secrets.APPLE_CERTS }}

      - name: Export
        run: make export

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 14.17

      - name: Upload ipa to AppCenter
        run: npx -p appcenter-cli appcenter distribute release -a Tuenti-Organization/Mistica-iOS -f ./build/ios.ipa -g Public --token ${{ secrets.APPCENTER_API_TOKEN }}
  
