name: CI

on:
  workflow_dispatch:
  pull_request:
        branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted-novum-mac

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Build and Test
        run: make test

      - name: Extract Sceenshot diff from failed Tests
        if: always()
        run: make extract_tests_attachments
        
      - name: Check Tests result
        uses: Telefonica/github-actions/mistica/upload-failed-screenshots@main
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          azure-account-name: ${{ secrets.AZURE_ACCOUNT_NAME }}
          azure-account-key: ${{ secrets.AZURE_ACCOUNT_KEY }}
          glob: 'tmp/test_output/diff_output/**/difference*.png'
          test-suite-and-test-name-regex: '(?<=diff_output\/)(.*)(?=\/difference)'
          test-suite-and-test-name-separator: '/'
          ci-container-name: 'mistica-ios-ci-container'
