name: CI

on:
  pull_request:
        branches: [main]

jobs:
  test:
    runs-on: self-hosted-novum-mac
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Clean tmp directory
        run: rm -rf tmp/*

      - name: Source bash profile
        run: source ~/.bash_profile

      - name: RubyGems Cache
        uses: actions/cache@v2.1.6
        with:
          path: vendor/bundle
          key: mistica-ios-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            mistica-ios-gems-
      
      - name: Carthage Cache
        uses: actions/cache@v2.1.6
        id: carthage-cache
        with:
          path: Carthage
          key: mistica-ios-carthage-${{ hashFiles('Cartfile.resolved') }}
          restore-keys: |
            mistica-ios-carthage-

      - name: Setup rbenv environment
        run: echo "~/.rbenv/shims" >> $GITHUB_PATH

      - name: Setup Ruby
        run: |
          rbenv install 2.6.0 -s
          rbenv local 2.6.0
          which ruby
          rbenv which ruby
      
      - name: Bundle Install
        run: |
          gem install bundle
          bundle config path vendor/bundle
          bundle install
      
      - name: Setup Project Dependencies
        run: bundle exec fastlane setup
      
      - name: Build and Test
        run: bundle exec fastlane test

      - name: Extract Sceenshot diff from failed Tests
        if: always()
        run: bundle exec fastlane extract_tests_attachments

      - name: Checkout Telefonica/github-actions repo
        uses: actions/checkout@v2
        if: always()
        with:
          repository: Telefonica/github-actions
          ref: 'v1.1.0'
          token: "${{ secrets.NOVUM_PRIVATE_REPOS }}"
          path: .github/actions

      - name: Check Tests result
        uses: ./.github/actions/mistica/upload-failed-screenshots
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          azure-account-name: ${{ secrets.AZURE_ACCOUNT_NAME }}
          azure-account-key: ${{ secrets.AZURE_ACCOUNT_KEY }}
          glob: 'tmp/test_output/diff_output/**/difference*.png'
          test-suite-and-test-name-regex: '(?<=diff_output\/)(.*)(?=\/difference)'
          test-suite-and-test-name-separator: '/'
          ci-container-name: 'mistica-ios-ci-container'
