name: Deploy catalog pull requests

on:
  push:
    branches: [master]

jobs:
  deploy-catalog-pull-requests:
    name: Deploy catalog pull requests
    runs-on: self-hosted-novum

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Checkout Telefonica/github-actions repo
        uses: actions/checkout@v2
        with:
          repository: Telefonica/github-actions
          token: "${{ secrets.READ_PRIVATE_REPOS }}"
          path: .github/actions

      - name: Deploy mistica catalog (cigen workflow)
        uses: ./.github/actions/novum/trigger-cigen-workflow
        with:
          workflow: build_and_deploy_mistica_catalog
          payload:  "ticket: APPS-7169"
