name: Deploy catalog pull requests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-catalog-pull-requests:
    name: Deploy catalog pull requests
    runs-on: ubuntu-latest
    
    steps:
      - uses: satak/webrequest-action@master
        with:
          url: https://flow.tuenti.io/events/FLOW/SCRIPT_EVENT
          method: POST
          payload: '{"script": "tu-ci", "operation": "create_or_update_job",  "repository": "mistica-ios",  "branch": "master",  "changeset": "${{ github.sha }}",  "workflow": "build_and_deploy_mistica_catalog",  "ticket": "APPS-7169", "username": "flow"}'