name: Regenerate screenshots

on:
  workflow_dispatch:

jobs:
  regenerate-screenshots:
    name: Regenerate screenshots
    runs-on: self-hosted-novum-mac
    steps:
      - name: Checkout
        uses: actions/checkout@v3             

      - name: Enable screenshots recording
        run: |
          sed -i '' 's/isRecording = false/isRecording = true/' Tests/MisticaSwiftUITests/UI/BadgeTests.swift
          
      - name: Launch tests
        run: make test
        
      - name: Enable screenshots recording
        run: |
          sed -i '' 's/isRecording = true/isRecording = false/' Tests/MisticaSwiftUITests/UI/BadgeTests.swift

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Regenerate screenshots
        env:
          GITHUB_TOKEN: ${{ secrets.NOVUM_PRIVATE_REPOS }}


