name: Regenerate screenshots

on:
  workflow_dispatch:

jobs:
  regenerate-screenshots:
    name: Regenerate screenshots
    runs-on: self-hosted-novum-mac
    steps:
      - name: Checkout
        uses: actions/checkout@v3             

      - name: Enable screenshots recording
        run: |
          find Tests/MisticaCommonTests -name "*.swift" -exec sed -i '' 's/isRecording = false/isRecording = true/' {} +
          find Tests/MisticaSwiftUITests -name "*.swift" -exec sed -i '' 's/isRecording = false/isRecording = true/' {} +
          find Tests/MisticaTests -name "*.swift" -exec sed -i '' 's/isRecording = false/isRecording = true/' {} +
          
      - name: Launch tests and regenerate screenshots
        run: make test
        continue-on-error: true
        
      - name: Disable screenshots recording
        run: |
          find Tests/MisticaCommonTests -name "*.swift" -exec sed -i '' 's/isRecording = false/isRecording = true/' {} +
          find Tests/MisticaSwiftUITests -name "*.swift" -exec sed -i '' 's/isRecording = true/isRecording = false/' {} +
          find Tests/MisticaTests -name "*.swift" -exec sed -i '' 's/isRecording = true/isRecording = false/' {} +

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Regenerate screenshots automatically from GH
        env:
          GITHUB_TOKEN: ${{ secrets.NOVUM_PRIVATE_REPOS }}


