name: Generate Mistica Tokens

on:
  workflow_dispatch:

concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

jobs:
  build:
    name: Build & generate tokens
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install
      working-directory: scripts/mistica-skin-generator

    - name: Generate tokens
      run: npm run generate
      working-directory: scripts/mistica-skin-generator

    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.NOVUM_PRIVATE_REPOS }}
        add-paths: 'Sources/MisticaCommon/*'
        commit-message: 'feat(skin): update design tokens'
        title: 'feat(skin): update design tokens from mistica-design'
        branch: 'import-design-tokens'
        # team-reviewers: 'ios'
        delete-branch: true
        draft: true
    - name: Show URL in summary annotation
      run: echo '::notice::Pull Request generated ${{ steps.create_pr.outputs.pull-request-url }}'