name: Manually deploy catalog

on:
  workflow_dispatch:
        inputs:
            commit_to_deploy:
                description: 'Changeset'
                required: false
                default: ''

jobs:
  manually-deploy-catalog:
    name: Manually deploy catalog
    runs-on: self-hosted-novum

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Checkout Telefonica/github-actions repo
        uses: actions/checkout@v2
        with:
          repository: Telefonica/github-actions
          token: "${{ secrets.NOVUM_PRIVATE_REPOS }}"
          path: .github/actions

      - name: Deploy master (cigen workflow)
        if: ${{ github.event.inputs.commit_to_deploy == '' }}
        uses: ./.github/actions/novum/trigger-cigen-workflow
        with:
          workflow: build_and_deploy_mistica_catalog
          branch: master
          payload: "ticket: APPS-7169"

      - name: Deploy commit (cigen workflow)
        if: ${{ github.event.inputs.commit_to_deploy != '' }}
        uses: ./.github/actions/novum/trigger-cigen-workflow
        with:
          workflow: build_and_deploy_mistica_catalog
          branch: master
          changeset: "${{ github.event.inputs.commit_to_deploy }}"
          payload: "ticket: APPS-7169"
