name: Release

on:
  workflow_dispatch:
    inputs:
      cliArgs:
        description: "CLI args"
        required: false
        default: "--debug"

jobs:
  release:
    name: Release
    runs-on: self-hosted-novum-mac

    steps:

      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.13.0

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.NOVUM_PRIVATE_REPOS }}
        run: npx -p @semantic-release/changelog -p @semantic-release/git -p @semantic-release/exec -p semantic-release@20.0.2 semantic-release ${{ github.event.inputs.cliArgs }}

      - name: Send Notification to Teams
        uses: Telefonica/github-actions/microsoft-teams/notify@main
        with:
          channel: ios_releases
