name: SwiftFormat
on:
  pull_request:
    branches:
      - '*'
jobs:
  format:
    name: SwiftFormat
    runs-on: self-hosted-novum-mac
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 12
        run: sudo xcode-select -s /Applications/Xcode-12.app
      - name: Format
        run: scripts/run_swiftformat.sh .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run swiftformat
        env:
          GITHUB_TOKEN: ${{ secrets.FLOW_GITHUB_TOKEN }}
