name: SwiftFormat
on:
  pull_request:
    branches:
      - '*'
jobs:
  format:
    name: SwiftFormat
    runs-on: self-hosted-novum-mac

    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
      
      - name: Format
        run: make format
      
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run swiftformat
        env:
          GITHUB_TOKEN: ${{ secrets.NOVUM_PRIVATE_REPOS }}
